GET https://api.themoviedb.org/3/movie/now_playing
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1NTUyZmRlMGVmMzE1MDQwZTA3M2FjMDc3NzQ4MGIwNiIsInN1YiI6IjY0YTZhOGMzY2FlNjMyMDExZmEzMjMwMyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ._DaUkZO060ZW-I63X4TkxACVu0cLawgcS2UdSo1sOKc